#!/usr/bin/python
'''
This python script is used to parse the log files generated by the individual processes 
and return the global state of the process given a snapshot id from those log files.  
'''

import sys, os

def main(argv):
	print 'Number of arguments:', len(sys.argv), 'arguments.'
	print 'Argument List:', str(sys.argv)
	snapshot = 'snapshot' + sys.argv[1]
	os.system("grep " + snapshot + " process_*_log.txt")

if __name__ == "__main__":
   main(sys.argv[1:])
